### ISSUE TITLE
Add benchmarks as a subproject; publish MetroHash results

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Zero-Allocation-Hashing#28]
Add JMH benchmarks as a subproject in this repository. Evaluate MetroHash performance and add the results to the table in README: https://github.com/OpenHFT/Zero-Allocation-Hashing#performance

**Comment by leventov** [comment]
Also wyhash

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/

**Comment by Azmisov** [comment]
Yes, would like to see benchmarks, since wyhash is one of the [fastest in smhasher tests](https://rurban.github.io/smhasher/doc/table.html), but wasn't benchmarked for the README. The results in the README don't align with the smhasher C++ results exactly, e.g. Murmur3 you'd expect to be first or second fastest; so I think benchmarks specifically for this Java implementation would be useful for people to see and pick one.
