### ISSUE TITLE
Release latest version to Maven central

### ISSUE THREAD

**Issue by paplorinc** [OpenHFT/Zero-Allocation-Hashing#52]
See:
* https://search.maven.org/artifact/net.openhft/zero-allocation-hashing
* https://mvnrepository.com/artifact/net.openhft/zero-allocation-hashing

Also, a changelog would be welcome since https://github.com/OpenHFT/Zero-Allocation-Hashing/releases doesn't include the actual releases and the readme contains old refrences to versions:

![image](https://user-images.githubusercontent.com/1841944/103883865-11692f80-50de-11eb-9da9-cf9c48d4a585.png)
and 
![image](https://user-images.githubusercontent.com/1841944/103883927-247bff80-50de-11eb-9797-ac4d55ec5251.png)
and 
![image](https://user-images.githubusercontent.com/1841944/103883972-35c50c00-50de-11eb-9e8a-22f153a3477d.png)

**Comment by paplorinc** [comment]
Any progress?

**Comment by gzm55** [comment]
@dpisklov could you do a release?

**Comment by RobAustin** [comment]
I will release it tomorrow.

**Comment by gzm55** [comment]
@RobAustin do you have time to do a release? or any others?

**Comment by gzm55** [comment]
0.15 is released, thanks @RobAustin

**Comment by RobAustin** [comment]
James. - If you want releases in the future please reach out to me on email me at rob.austin(at)chronicle.software as I don’t follow the git issues on this project all the time. I also suggest you use a subject on the email like “Please release Zero-Allocation-Hashing“, so that it stands out. sorry for taking a while to release it on this occasion.

**Comment by gzm55** [comment]
@RobAustin it's OK.

**Comment by RobAustin** [comment]
It’s up to you. I track emails more than git issues on this project.
