### ISSUE TITLE
Request for confirmation of "new" release number scheme

### ISSUE THREAD

**Issue by p4654545** [OpenHFT/Zero-Allocation-Hashing#89]
The latest release appeared as 'net.openhft:zero-allocation-hashing:0.26ea0' (instead of version 0.17) and I was wondering whether this is intentional? Just checking before accepting it.

**Comment by tgd** [comment]
Hi @p4654545 thanks for reaching out. This is indeed intentional as we start to roll out the x.26 release of OpenHFT code. You can find some further description of the release methodology here: https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc

The reason you see such a large jump in version numbers here is that this repo has not been released for some time. In this latest release. 

The EA in the release version corresponds to "early access", these represent our latest releases. Stable releases are also available but only for enterprise customers. If you would like to discuss the enterprise route with us please contact us here: https://chronicle.software/contact-us/
