### ISSUE TITLE
128 bit Hash

### ISSUE THREAD

**Issue by hasswen** [OpenHFT/Zero-Allocation-Hashing#9]
Thank you for the awesome library!  Is it possible to add a 128-bit version for one of the hash functions, such as Murmur3?

**Comment by leventov** [comment]
The problem is that there is no 128-bit primitive type in Java. So the lib should either return something like `Result` object with two `long` fields, that directly violates "zero-allocation" promise, carried to the library name. (I still don't trust Hotspot's escape analysis much and never rely on this feature.) Or, pass additional argument (of the same `Result` type) to all methods, that is very cumbersome, and would probably still require the lib user to keep this `Result` object somewhere in ThreadLocals.

**Comment by mrniko** [comment]
@hasswen  I joined two hashes FarmHash and xxHash to get 128-bit hash: 

```java
    private byte[] hash(byte[] objectState) {
        long h1 = LongHashFunction.farmUo().hashBytes(objectState);
        long h2 = LongHashFunction.xx_r39().hashBytes(objectState);

        return ByteBuffer.allocate((2 * Long.SIZE) / Byte.SIZE)
                .putLong(h1)
                .putLong(h2)
                .array();
    }
```

**Comment by steffenyount** [comment]
Two other options for returning a 128-bit xxHash result with "zero-allocation" would be:

1. pass a functional interface argument, that would be called to set both the hi/low long values before the function returns.
2. pass a byte[16] array argument, that would be populated before the function returns.

It would be really interesting to see if the xxHash's high performance numbers can be extended to a 128-bit hash.

**Comment by leventov** [comment]
@steffenyount instead of byte[] array it seems better to me to create a specialized `Int128` class with two mutable long fields, because it is smaller (no need for array.length field), more safety (no need to check that array length is indeed 16) and easier to extract long words from it.

Do you have incentives to implement this?

**Comment by gzm55** [comment]
Another interface using lambda:

```java
long hash128(..., LongBinaryOperator readAll) {
  // computing
  // internal result in low and high

  return readAll.applyAsLong(low, high);
}

class A{
long lowHolderField, highHolderField;
void main() {
  long low = hash128(..., h -> { lowHolderField = l; highHolderField = h; return l; });
}
}
```

OR

```java
long hash128(..., LongConsumer readHigh) {
  // computing
  // internal result in low and high
  if (null != readHigh) {
   readHigh.accept(high);
  }
  return low;
}

class A{
long highHolderField;
void main() {
  long low = hash128(..., h -> {highHolderField = h;});
}
}
```

**Comment by gzm55** [comment]
> instead of byte[] array it seems better to me to create a specialized Int128 class with two mutable long fields, because it is smaller (no need for array.length field)

@leventov Using jol, we can see `array.length` is merge into the object header, at offset 12 size 4, so `long[2]` and `Int128` will be the same size in memory (32bytes). But still `Int128` can avoid size checking.

**Comment by gzm55** [comment]
@leventov #34 is a working proposal for 128 or more bit hash.
